### ISSUE TITLE
Problems with Warcraft II: Beyond The Dark Portal

### ISSUE THREAD

**Issue by dbenoy** [adoxa/shsucd#2]
When using SHSUCDX to play Warcraft II's expansion, I get an error about an incorrect file version. The problem doesn't happen on the same system when using MSCDEX instead.

I believe it may be copy protection that relies on some sort of quirk of MSCDEX. When I'm using SHSUCDX I see that \DATA\MUDDAT.CUD and \DATA\SNDDAT.WAR files each appear _twice_ in the directory listing. When I'm using MSCDEX I only see one of each. MSCDEX sees the larger files, and the smaller files are quite tiny, so I think the smaller files are there to trick other CD filesystem drivers into seeing the wrong data, perhaps?

archive.org seems to have a copy of this disc (although I'm using an original disc, so maybe it's a different version. If you can't reproduce it let me know and I'll dump my disc) https://archive.org/details/Warcraft2BeyondTheDarkPortal

**Comment by dbenoy** [comment]
![PXL_20220901_035509736](https://user-images.githubusercontent.com/2285331/187830089-34685c79-02c1-49b2-b50b-3f52e7dbe32a.jpg)
![PXL_20220901_035707576](https://user-images.githubusercontent.com/2285331/187830102-50b9702a-c0e6-402b-8978-5aed04bcf0af.jpg)

**Comment by dbenoy** [comment]
I'm using FreeDOS 1.3, as well, and the SHSUCDX included in there. Hopefully I'm reporting this in the right place.

**Comment by adoxa** [comment]
You are reporting in the right place. I wasn't able to reproduce it with the archive image, so a dump would be appreciated (the first 64k would be sufficient).

**Comment by dbenoy** [comment]
[64kdump.zip](https://github.com/adoxa/shsucd/files/9471508/64kdump.zip)

Just for posterity for anyone searching up this issue, to the best of my recollection (which may be flawed, it's been some time) this is the Warcraft Battle Chest release which contained Warcraft 1 and 2 and this expansion disc. It may also have included Warcraft 3 and its expansion. I can't recall. I purchased it in Canada.

![PXL_20220901_160942416](https://user-images.githubusercontent.com/2285331/187962011-d784ba32-093c-408c-a699-6d2c27c8e70d.jpg)
![PXL_20220901_160214425](https://user-images.githubusercontent.com/2285331/187962018-c6b24a04-de8d-4b21-9424-d942ceb774cb.jpg)

**Comment by adoxa** [comment]
Confirm this works for you and I'll make a new release.
[shsucdx.com.gz](https://github.com/adoxa/shsucd/files/9474481/shsucdx.com.gz)

The problem was due to "Associated Files", so probably something to do with the Mac version. Those files are now skipped.

**Comment by dbenoy** [comment]
Fantastic! It works. Directory listing no longer has duplicates, software installs as expected, and software runs as expected. :+1:
